# SPDX-License-Identifier: MIT-0
---
# tasks file for baseline
- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: true

- name: Remove unused packages
  ansible.builtin.dnf:
    name: "{{ baseline_remove_packages }}"
    state: absent
  when: baseline_remove_packages is defined

- name: Install baseline packages
  ansible.builtin.dnf:
    name: "{{ baseline_packages }}"
    state: present
  when: baseline_packages is defined
  become: true

- name: Configure timezone
  community.general.timezone:
    name: "{{ baseline_timezone }}"
  when: baseline_timezone is defined
  become: true

- name: Configure /etc/issue to appear
  become: true
  block:
    - name: Set SSH Banner
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner '
        line: 'Banner /etc/issue'
        state: present
        backrefs: true

    - name: Reload SSHD
      ansible.builtin.systemd:
        name: sshd
        state: reloaded

    - name: Confgure /etc/issue
      ansible.builtin.template:
        src: issue.j2
        dest: /etc/issue
        owner: root
        group: root
        mode: '0644'

- name: Configure motd
  ansible.builtin.template:
    src: motd.sh.j2
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure custom bash prompt
  ansible.builtin.template:
    src: sh.local.j2
    dest: /etc/profile.d/sh.local
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure Podman
  when: baseline_podman
  become: true
  block:
    - name: Install Podman
      ansible.builtin.dnf:
        name:
          - podman
        state: present

    - name: Configure Podman socket
      ansible.builtin.systemd:
        name: podman.socket
        state: started
        enabled: true

- name: Configure cockpit
  when: baseline_cockpit
  become: true
  block:
    - name: Install Cockpit
      vars:
        cockpit_packages:
          - cockpit
          - cockpit-podman
          - cockpit-networkmanager
          - cockpit-storaged
          - cockpit-file-sharing
          - cockpit-bridge
        cockpit_manage_firewall: false
        cockpit_port: 9090
        cockpit_config:
          WebService:
            Origins: "https://cockpit.{{ inventory_hostname }}"
          Session:
            IdleTimeout: 15
            Banner: "/etc/issue"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.cockpit
